apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    app: backend
spec:
  containers: 
  - name: my-container
    image: nginx:latest
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
